### ISSUE TITLE
CLI - AttributeError: object has no attribute 'title'

### ISSUE THREAD

**Issue by samisnotinsane** [samisnotinsane/podster#11]
Occurs when using this command: `python podster.py store --create`

`KeyError: 'title'`

```
Traceback (most recent call last):
  File "podster.py", line 139, in <module>
    cli()
  File "/Users/sameenislam/anaconda3/envs/pypod/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/Users/sameenislam/anaconda3/envs/pypod/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/Users/sameenislam/anaconda3/envs/pypod/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/sameenislam/anaconda3/envs/pypod/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/sameenislam/anaconda3/envs/pypod/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "podster.py", line 59, in store
    show_data = extract_fields(cleanline, parsed_data)
  File "podster.py", line 93, in extract_fields
    channel_title = channel.title
  File "/Users/sameenislam/anaconda3/envs/pypod/lib/python3.7/site-packages/feedparser.py", line 400, in __getattr__
    raise AttributeError("object has no attribute '%s'" % key)
AttributeError: object has no attribute 'title'
```

**Comment by samisnotinsane** [comment]
Fixed in PR #12
